[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_FRAPPE_URL = "https://qswr.sa"
  GENERATE_SOURCEMAP = "false"
